-- DB SCHEMA 생성
create database testdb;

-- SCHEMA를 사용하도록 접속 수행
USE emsDB;

create table tbl_bbs (
	BBS_ID	BIGINT PRIMARY KEY AUTO_INCREMENT,
	BBS_P_ID	BIGINT	DEFAULT 0,
	BBS_WRITER	nVARCHAR(50)	NOT NULL,
	BBS_DATE	VARCHAR(10),
	BBS_TIME	VARCHAR(10),
	BBS_SUBJECT	nVARCHAR(125),
	BBS_CONTENT	nVARCHAR(1000),
	BBS_COUNT	INT	DEFAULT 0
);

desc tbl_bbs;

DROP TABLE tbl_comment;

create table tbl_comment (
	CMT_ID	BIGINT	NOT NULL	PRIMARY KEY AUTO_INCREMENT,
	CMT_P_ID	BIGINT	DEFAULT 0,
	CMT_WRITER	VARCHAR(20)	NOT NULL,
	CMT_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
	CMT_TEXT	VARCHAR(400)
);

SELECT * FROM tbl_comment;